version: "3.7"
services:
  superset:
    image: phenya28/superset:apache-superset 
    ports:
      - "8085:8088"
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=BiMJbGJthWHmBOKfYII8zntacJM3ETv1sgoO3cmJiR4NZ8OdWehNsisV
      - SUPERSET_PASSWORD=123qweASD
      - SUPERSET_USERNAME=admin
    restart: unless-stopped
    volumes:
      - superset:/app 

volumes:
  superset:
